# New Section

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# !nvidia-smi

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
data = '/content/drive/MyDrive/data/Suicide_Detection.csv'
df = pd.read_csv(data)
df = df.iloc[:,1:]
df.head()

text        class
0  Ex Wife Threatening SuicideRecently I left my ...      suicide
1  Am I weird I don't get affected by compliments...  non-suicide
2  Finally 2020 is almost over... So I can never ...  non-suicide
3          i need helpjust help me im crying so hard      suicide
4  I’m so lostHello, my name is Adam (16) and I’v...      suicide

In [ ]:
df['class'].value_counts()

suicide        116037
non-suicide    116037
Name: class, dtype: int64

In [ ]:
num_classes = 2
print(len(df['class'].unique()))

2


In [ ]:
class_names = ['suicide','non-suicide']
print(df['class'].unique())

['suicide' 'non-suicide']


In [ ]:
df_sui = df[df['class']=='suicide'][0:20000]
df_non_sui = df[df['class']=='non-suicide'][0:20000]

data=pd.concat([df_sui, df_non_sui],axis=0)

from sklearn.utils import shuffle
df = shuffle(data, random_state=0)
df.reset_index(drop=True, inplace=True)
df

text        class
0      The people that are telling me to go on living...      suicide
1      For all the young people out there....So first...      suicide
2      Death=Ultimate freedomWe're never really free ...      suicide
3      The more I try to get help, the more I realise...      suicide
4      If my parents didn't buy my cell phone, do the...  non-suicide
...                                                  ...          ...
39995  Nothing like the simulations. My leg hair move...  non-suicide
39996  I can't find my fucking phone What the hell do...  non-suicide
39997  What should I get for a former student of mine...  non-suicide
39998         MERRY CHRISTMAS EVERYONE! Merry Christmas!  non-suicide
39999  Gf is laying next to me, screaming she wants t...      suicide

[40000 rows x 2 columns]

In [ ]:
import re
from nltk.tokenize import word_tokenize

def clean_text(data):
    
    # remove hashtags and @usernames
    data = re.sub(r'http\S+', '', data)
    data = re.sub('[^a-zA-Z]', ' ', data)
    
    # Lowering Text
    data = data.lower()
    data = word_tokenize(data)
    
    return data

In [ ]:
import nltk
nltk.download('punkt')
texts = [' '.join(clean_text(text)) for text in df.text]

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [ ]:
texts[0:2]

['the people that are telling me to go on living are the same people causing me to kill myselfi m talking about my parents i mean they aren t abuse or anything like that it s just i care too much about them they definitely have they re flaws and thats it my mom constantly screams at me telling me to work and of course i can t cause of my severe anxiety and my dad doesn t care or he just doesn t want to deal with me fuck my life i ll just end it as soon as possible anyways i m sicl of being human',
 'for all the young people out there so first off this isn t an attention whoring post or anything i m browsing these threads and seeing a lot of young people feeling like they ve got nothing left for them so i want them to know it ll be ok hopefully this could be encouraging to someone this could get long when i was i developed depression i remember crying in the kitchen one night and telling my mom that i wanted to die went to therapy got the pills and all that i m almost now and am not cur

In [ ]:
def combineData(data):
    lst = []
    for i in data:
        lst.append(i)
        
    my_lst_str = ''.join(map(str, lst))
    return my_lst_str

val = pd.DataFrame({"values":texts})
val.head()

values
0  the people that are telling me to go on living...
1  for all the young people out there so first of...
2  death ultimate freedomwe re never really free ...
3  the more i try to get help the more i realise ...
4  if my parents didn t buy my cell phone do they...

In [ ]:
val['class'] = df['class']
val.head()

values        class
0  the people that are telling me to go on living...      suicide
1  for all the young people out there so first of...      suicide
2  death ultimate freedomwe re never really free ...      suicide
3  the more i try to get help the more i realise ...      suicide
4  if my parents didn t buy my cell phone do they...  non-suicide

In [ ]:
val['class'] = val['class'].map({'suicide':0, 'non-suicide':1})
val.head()

values  class
0  the people that are telling me to go on living...      0
1  for all the young people out there so first of...      0
2  death ultimate freedomwe re never really free ...      0
3  the more i try to get help the more i realise ...      0
4  if my parents didn t buy my cell phone do they...      1

In [ ]:
X = val['values']
y = val['class']

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
voc_size = 10000

In [ ]:
msg = X.copy()
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(val['values'])):
    data = re.sub('[^a-zA-Z]', ' ', val['values'][i])
    data = data.lower()
    data = data.split()

    data = [ps.stem(word) for word in data if not word in stopwords.words('english')]
    data = ' '.join(data)
    corpus.append(data)

In [ ]:
corpus[0:2]

['peopl tell go live peopl caus kill myselfi talk parent mean abus anyth like care much definit flaw that mom constantli scream tell work cours caus sever anxieti dad care want deal fuck life end soon possibl anyway sicl human',
 'young peopl first attent whore post anyth brows thread see lot young peopl feel like got noth left want know ok hope could encourag someon could get long develop depress rememb cri kitchen one night tell mom want die went therapi got pill almost current medic sent mental hospit coupl week year ago sever type medic still life keep get better that tri say know everyon els say young want hear get better grow get control life love love hate job get easier deal ye still hurt ye still depress deal realiz broken need littl jump start peopl need littl thing seem imposs terrifi bad tip think find special person make everyth better sound cold need figur assum answer put everyth girl zing made huge mistak tell live peopl normal freak also break told want kill much emot 

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot
onehot_rep = [one_hot(words, voc_size) for words in corpus] 
print(onehot_rep[0:2])

[[7811, 2504, 2261, 125, 7811, 5925, 5646, 3405, 8156, 6832, 5615, 1967, 9441, 4896, 2022, 9926, 8370, 6552, 7658, 7354, 408, 4758, 2504, 3764, 9763, 5925, 6905, 6984, 7455, 2022, 9438, 9339, 5704, 4661, 7117, 6117, 9022, 3344, 4930, 2804], [3915, 7811, 9066, 2759, 9170, 4762, 9441, 722, 6562, 3279, 1798, 3915, 7811, 3920, 4896, 7080, 2652, 2939, 9438, 3192, 9436, 7222, 8089, 7658, 1829, 8089, 4545, 8038, 8312, 8499, 3280, 3989, 4808, 7075, 2739, 2504, 7354, 9438, 8723, 3431, 7453, 7080, 721, 7082, 5511, 7460, 2904, 2249, 207, 522, 9953, 2263, 7405, 6905, 3437, 7460, 1744, 4661, 6070, 4545, 4451, 7658, 8520, 1756, 3192, 9637, 7935, 1756, 3915, 9438, 6402, 4545, 4451, 706, 4545, 1193, 4661, 2770, 2770, 9457, 5918, 4545, 6712, 9339, 5367, 1744, 6126, 5367, 1744, 8499, 9339, 9003, 2599, 1503, 9004, 6603, 2551, 7811, 1503, 9004, 3521, 4579, 1277, 1971, 4716, 8838, 1787, 7625, 8818, 5657, 7041, 3089, 4451, 4386, 8018, 1503, 4459, 4163, 949, 150, 3089, 6385, 5632, 5733, 2484, 9185, 2504, 125

In [ ]:
max(len(l) for l in onehot_rep)

5850

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
sent_len = 5850
embedded_docs = pad_sequences(onehot_rep, padding='pre', maxlen=sent_len)
print(embedded_docs)

[[   0    0    0 ... 3344 4930 2804]
 [   0    0    0 ... 1744 8502 2770]
 [   0    0    0 ... 6219 6018 3323]
 ...
 [   0    0    0 ... 3344 9677   92]
 [   0    0    0 ... 9637 6071 5922]
 [   0    0    0 ... 3764 2770 9747]]


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Bidirectional, Dropout, Embedding, GRU
from tensorflow.keras.callbacks import EarlyStopping

embedding_vector_features=100
sent_len = 5850
voc_size = 10000

model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_len))
model.add(Dropout(0.5))

model.add(LSTM(64,return_sequences=True))
model.add(Dropout(0.5))

model.add(LSTM(10))
model.add(Dropout(0.5))

model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

In [ ]:
X_final = np.array(embedded_docs)
y_final = np.array(y)

X_final.shape, y_final.shape

((40000, 5850), (40000,))

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_final,y_final,test_size=0.2)

In [ ]:
early_stop = EarlyStopping(monitor='val_loss', patience=5, verbose=1, mode='min')

model.fit(X_train, y_train,epochs=100,batch_size=64,validation_data=(X_test, y_test),callbacks=[early_stop])

In [ ]:
y_pred = (model.predict(X_test) > 0.5).astype("int32")
y_pred

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

confusion_matrix(y_test,y_pred)

# array([[3650,  348],
#        [ 352, 3650]])


In [ ]:
accuracy_score(y_test, y_pred)  #0.9125

In [ ]:
model.save('/content/drive/MyDrive/TweetData/Depression_LSTM_output.h5')

# Bidirectional-LSTM

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Bidirectional, Dropout, Embedding, GRU
from tensorflow.keras.callbacks import EarlyStopping

embedding_vector_features=100
sent_len = 5850
voc_size = 10000

model2=Sequential()
model2.add(Embedding(voc_size,embedding_vector_features,input_length=sent_len))
model2.add(Dropout(0.5))

model2.add(Bidirectional(LSTM(64,return_sequences=True)))
model2.add(Dropout(0.5))

model2.add(Bidirectional(LSTM(10)))
model2.add(Dropout(0.5))

model2.add(Dense(1,activation='sigmoid'))
model2.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model2.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5850, 100)         1000000   
                                                                 
 dropout (Dropout)           (None, 5850, 100)         0         
                                                                 
 bidirectional (Bidirectiona  (None, 5850, 128)        84480     
 l)                                                              
                                                                 
 dropout_1 (Dropout)         (None, 5850, 128)         0         
                                                                 
 bidirectional_1 (Bidirectio  (None, 20)               11120     
 nal)                                                            
                                                                 
 dropout_2 (Dropout)         (None, 20)                0

In [ ]:
early_stop = EarlyStopping(monitor='val_loss', patience=5, verbose=1, mode='min')

model2.fit(X_train, y_train,epochs=100,batch_size=64,validation_data=(X_test, y_test),callbacks=[early_stop])

Epoch 1/100
500/500 [==============================] - 368s 714ms/step - loss: 0.3591 - accuracy: 0.8606 - val_loss: 0.2283 - val_accuracy: 0.9194
Epoch 2/100
500/500 [==============================] - 358s 715ms/step - loss: 0.2296 - accuracy: 0.9242 - val_loss: 0.2231 - val_accuracy: 0.9147
Epoch 3/100
500/500 [==============================] - 357s 715ms/step - loss: 0.2003 - accuracy: 0.9348 - val_loss: 0.2177 - val_accuracy: 0.9201
Epoch 4/100
500/500 [==============================] - 357s 715ms/step - loss: 0.1766 - accuracy: 0.9426 - val_loss: 0.2194 - val_accuracy: 0.9180
Epoch 5/100
500/500 [==============================] - 358s 716ms/step - loss: 0.1559 - accuracy: 0.9503 - val_loss: 0.2408 - val_accuracy: 0.9134
Epoch 6/100
500/500 [==============================] - 362s 723ms/step - loss: 0.1447 - accuracy: 0.9531 - val_loss: 0.2925 - val_accuracy: 0.9111
Epoch 7/100
500/500 [==============================] - 358s 716ms/step - loss: 0.1361 - accuracy: 0.9569 - val_loss: 0

In [ ]:
model2.save('/content/drive/MyDrive/TweetData/Depression_BI_LSTM_output.h5')